// Package remoteopen hands generated localhost session URLs to the operating
// system. It rejects every non-loopback destination.
package remoteopen

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/url"
	"os/exec"
	"runtime"
	"strings"
)

// Validate accepts only plain HTTP loopback URLs generated by the ephemeral
// local broker. User-configured and hosted URLs are deliberately unsupported.
func Validate(target string) (string, error) {
	target = strings.TrimSpace(target)
	if target == "" {
		return "", errors.New("remote URL is not configured")
	}
	if strings.ContainsAny(target, "\r\n\x00") {
		return "", errors.New("remote URL contains control characters")
	}
	parsed, err := url.Parse(target)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return "", errors.New("remote URL must include a scheme and host")
	}
	if strings.ToLower(parsed.Scheme) != "http" {
		return "", fmt.Errorf("localhost remote URL scheme %q is not supported", parsed.Scheme)
	}
	hostname := strings.ToLower(parsed.Hostname())
	ip := net.ParseIP(hostname)
	if hostname != "localhost" && (ip == nil || !ip.IsLoopback()) {
		return "", errors.New("remote URL must use a loopback host")
	}
	if parsed.User != nil {
		return "", errors.New("remote URL must not contain a username or password")
	}
	if parsed.RawQuery != "" || parsed.Fragment != "" {
		return "", errors.New("remote URL must not contain a query string or fragment")
	}
	return parsed.String(), nil
}

// Command returns the shell-free OS handoff command for a validated URL.
func Command(ctx context.Context, target string) (*exec.Cmd, error) {
	validated, err := Validate(target)
	if err != nil {
		return nil, err
	}
	switch runtime.GOOS {
	case "darwin":
		return exec.CommandContext(ctx, "open", validated), nil
	case "windows":
		return exec.CommandContext(ctx, "rundll32.exe", "url.dll,FileProtocolHandler", validated), nil
	default:
		return exec.CommandContext(ctx, "xdg-open", validated), nil
	}
}

// Open hands the URL to the operating system and returns as soon as the
// external application starts.
func Open(ctx context.Context, target string) error {
	cmd, err := Command(ctx, target)
	if err != nil {
		return err
	}
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("open remote session: %w", err)
	}
	return cmd.Process.Release()
}
